// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Gender represents the patient's gender identity.
 * @readonly
 * @enum {string}
 */
export const Gender = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    GenderMale: "male",
    GenderFemale: "female",
    GenderOther: "other",
    GenderUndisclosed: "undisclosed",
};

/**
 * Patient represents a dental patient demographic record.
 */
export class Patient {
    /**
     * Creates a new Patient instance.
     * @param {Partial<Patient>} [$$source = {}] - The source object to create the Patient.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("first_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["first_name"] = "";
        }
        if (!("last_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["middle_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["preferred_name"] = undefined;
        }
        if (!("date_of_birth" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date_of_birth"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("gender" in $$source)) {
            /**
             * @member
             * @type {Gender}
             */
            this["gender"] = Gender.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["email"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["phone_primary"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["phone_secondary"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["address_line1"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["address_line2"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["city"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["state"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["zip_code"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["medical_alerts"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["allergies"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["notes"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Patient instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Patient}
     */
    static createFrom($$source = {}) {
        const $$createField15_0 = $$createType0;
        const $$createField16_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("medical_alerts" in $$parsedSource) {
            $$parsedSource["medical_alerts"] = $$createField15_0($$parsedSource["medical_alerts"]);
        }
        if ("allergies" in $$parsedSource) {
            $$parsedSource["allergies"] = $$createField16_0($$parsedSource["allergies"]);
        }
        return new Patient(/** @type {Partial<Patient>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
