// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * @param {domain$0.Patient | null} p
 * @returns {$CancellablePromise<domain$0.Patient | null>}
 */
export function CreatePatient(p) {
    return $Call.ByID(3808660610, p).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<domain$0.Patient | null>}
 */
export function GetPatient(id) {
    return $Call.ByID(2982187380, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<(domain$0.Patient | null)[]>}
 */
export function ListPatients(query) {
    return $Call.ByID(3480976879, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {domain$0.Patient | null} p
 * @returns {$CancellablePromise<domain$0.Patient | null>}
 */
export function UpdatePatient(p) {
    return $Call.ByID(1696936265, p).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = domain$0.Patient.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
