package demo

import (
	"context"
	"fmt"
	"time"

	"github.com/LibreDental/libredental/internal/domain"
	"github.com/LibreDental/libredental/internal/storage/sqlite"
)

func seedPatients(ctx context.Context, patientRepo *sqlite.PatientRepository, now time.Time, summary *SeedSummary) error {
	patients := []*domain.Patient{
		{
			ID:                     "pat_101",
			FirstName:              "Johnathan",
			LastName:               "Miller",
			DateOfBirth:            time.Date(1985, 4, 12, 0, 0, 0, 0, time.UTC),
			Sex:                    domain.SexMale,
			Email:                  "j.miller@example.com",
			PhonePrimary:           "(555) 111-2233",
			PhoneSecondary:         "(555) 111-9988",
			EmergencyContactName:   "Sarah Miller",
			EmergencyContactRel:    "Spouse",
			EmergencyContactPhone:  "(555) 111-8899",
			GuarantorName:          "Self",
			GuarantorRel:           "Self",
			GuarantorPhone:         "(555) 111-2233",
			InsuranceCarrier:       "Delta Dental PPO",
			InsurancePolicyNumber:  "DEL-9948201",
			InsuranceGroupNumber:   "GRP-10023",
			PreferredContactMethod: "phone",
			PreferredLanguage:      "en",
			ReminderOptIn:          true,
			PreferredProviderID:    "prov_101",
			ReferralSource:         "Doctor Referral",
			AddressLine1:           "742 Evergreen Terrace",
			City:                   "San Francisco",
			StateProvince:          "CA",
			PostalCode:             "94107",
			CountryCode:            domain.CountryUS,
			NationalIDType:         "ssn",
			NationalID:             "123-45-6789",
			MedicalAlerts:          []string{"High Blood Pressure", "Latex Allergy"},
			Allergies:              []string{"Latex"},
			Notes:                  "Prefers morning appointments.",
			Status:                 domain.StatusActive,
			CreatedAt:              now,
			UpdatedAt:              now,
			Version:                1,
		},
		{
			ID:                     "pat_102",
			FirstName:              "Sophia",
			LastName:               "Martinez",
			DateOfBirth:            time.Date(1992, 9, 24, 0, 0, 0, 0, time.UTC),
			Sex:                    domain.SexFemale,
			Email:                  "sophia.m@example.com",
			PhonePrimary:           "(555) 222-3344",
			PhoneSecondary:         "(555) 222-7766",
			EmergencyContactName:   "Carlos Martinez",
			EmergencyContactRel:    "Brother",
			EmergencyContactPhone:  "(555) 222-9900",
			GuarantorName:          "Self",
			GuarantorRel:           "Self",
			GuarantorPhone:         "(555) 222-3344",
			InsuranceCarrier:       "Cigna Dental Health",
			InsurancePolicyNumber:  "CGN-3310492",
			InsuranceGroupNumber:   "GRP-44012",
			PreferredContactMethod: "email",
			PreferredLanguage:      "en",
			ReminderOptIn:          true,
			PreferredProviderID:    "prov_103",
			ReferralSource:         "Online Search",
			AddressLine1:           "1280 Mission Street, Apt 4B",
			City:                   "San Francisco",
			StateProvince:          "CA",
			PostalCode:             "94103",
			CountryCode:            domain.CountryUS,
			NationalIDType:         "ssn",
			NationalID:             "987-65-4321",
			MedicalAlerts:          []string{"Penicillin Allergy", "Asthma"},
			Allergies:              []string{"Penicillin"},
			Notes:                  "Pre-medicate with non-penicillin antibiotic before invasive procedures.",
			Status:                 domain.StatusActive,
			CreatedAt:              now,
			UpdatedAt:              now,
			Version:                1,
		},
		{
			ID:                     "pat_103",
			FirstName:              "Robert",
			LastName:               "Chen",
			DateOfBirth:            time.Date(1968, 11, 5, 0, 0, 0, 0, time.UTC),
			Sex:                    domain.SexMale,
			Email:                  "r.chen@example.com",
			PhonePrimary:           "(555) 333-4455",
			EmergencyContactName:   "Mei Chen",
			EmergencyContactRel:    "Spouse",
			EmergencyContactPhone:  "(555) 333-8811",
			InsuranceCarrier:       "MetLife Dental",
			InsurancePolicyNumber:  "MET-8840192",
			InsuranceGroupNumber:   "GRP-88102",
			PreferredContactMethod: "sms",
			PreferredLanguage:      "en",
			ReminderOptIn:          true,
			PreferredProviderID:    "prov_102",
			ReferralSource:         "Word of Mouth",
			AddressLine1:           "450 Sutter Street",
			City:                   "San Francisco",
			StateProvince:          "CA",
			PostalCode:             "94108",
			CountryCode:            domain.CountryUS,
			NationalIDType:         "ssn",
			NationalID:             "456-78-9012",
			MedicalAlerts:          []string{"Type II Diabetes"},
			Allergies:              []string{},
			Notes:                  "Monitor blood sugar level before surgical visits.",
			Status:                 domain.StatusActive,
			CreatedAt:              now,
			UpdatedAt:              now,
			Version:                1,
		},
		{
			ID:                     "pat_104",
			FirstName:              "Emma",
			LastName:               "Watson",
			DateOfBirth:            time.Date(2001, 3, 18, 0, 0, 0, 0, time.UTC),
			Sex:                    domain.SexFemale,
			Email:                  "ewatson@example.com",
			PhonePrimary:           "(555) 444-5566",
			EmergencyContactName:   "David Watson",
			EmergencyContactRel:    "Father",
			EmergencyContactPhone:  "(555) 444-9911",
			InsuranceCarrier:       "Guardian Dental",
			InsurancePolicyNumber:  "GRD-1192039",
			InsuranceGroupNumber:   "GRP-11045",
			PreferredContactMethod: "email",
			PreferredLanguage:      "en",
			ReminderOptIn:          true,
			PreferredProviderID:    "prov_103",
			ReferralSource:         "Insurance Directory",
			AddressLine1:           "88 King Street",
			City:                   "San Francisco",
			StateProvince:          "CA",
			PostalCode:             "94107",
			CountryCode:            domain.CountryUS,
			NationalIDType:         "ssn",
			NationalID:             "321-65-9874",
			MedicalAlerts:          []string{},
			Allergies:              []string{},
			Notes:                  "Clean medical record.",
			Status:                 domain.StatusActive,
			CreatedAt:              now,
			UpdatedAt:              now,
			Version:                1,
		},
		{
			ID:                     "pat_105",
			FirstName:              "David",
			LastName:               "O'Connor",
			DateOfBirth:            time.Date(1955, 7, 30, 0, 0, 0, 0, time.UTC),
			Sex:                    domain.SexMale,
			Email:                  "doconnor@example.com",
			PhonePrimary:           "(555) 555-6677",
			EmergencyContactName:   "Mary O'Connor",
			EmergencyContactRel:    "Spouse",
			EmergencyContactPhone:  "(555) 555-0022",
			InsuranceCarrier:       "Humana Dental Choice",
			InsurancePolicyNumber:  "HUM-7740291",
			InsuranceGroupNumber:   "GRP-77201",
			PreferredContactMethod: "phone",
			PreferredLanguage:      "en",
			ReminderOptIn:          true,
			PreferredProviderID:    "prov_101",
			ReferralSource:         "Doctor Referral",
			AddressLine1:           "300 California Street",
			City:                   "San Francisco",
			StateProvince:          "CA",
			PostalCode:             "94104",
			CountryCode:            domain.CountryUS,
			NationalIDType:         "ssn",
			NationalID:             "654-98-3210",
			MedicalAlerts:          []string{"Anticoagulant Therapy (Warfarin)"},
			Allergies:              []string{},
			Notes:                  "Check INR value prior to extractions.",
			Status:                 domain.StatusActive,
			CreatedAt:              now,
			UpdatedAt:              now,
			Version:                1,
		},
		{
			ID:                     "pat_106",
			FirstName:              "Mia",
			LastName:               "Tanaka",
			DateOfBirth:            time.Date(1998, 12, 14, 0, 0, 0, 0, time.UTC),
			Sex:                    domain.SexFemale,
			Email:                  "mia.t@example.com",
			PhonePrimary:           "(555) 666-7788",
			EmergencyContactName:   "Kenji Tanaka",
			EmergencyContactRel:    "Parent",
			EmergencyContactPhone:  "(555) 666-4433",
			InsuranceCarrier:       "Aetna Dental",
			InsurancePolicyNumber:  "AET-5540192",
			InsuranceGroupNumber:   "GRP-55102",
			PreferredContactMethod: "sms",
			PreferredLanguage:      "en",
			ReminderOptIn:          true,
			PreferredProviderID:    "prov_102",
			ReferralSource:         "Social Media",
			AddressLine1:           "1500 Van Ness Avenue",
			City:                   "San Francisco",
			StateProvince:          "CA",
			PostalCode:             "94109",
			CountryCode:            domain.CountryUS,
			NationalIDType:         "ssn",
			NationalID:             "789-12-3456",
			MedicalAlerts:          []string{"Nitrous Oxide Sensitivity"},
			Allergies:              []string{},
			Notes:                  "Interested in cosmetic whitening.",
			Status:                 domain.StatusActive,
			CreatedAt:              now,
			UpdatedAt:              now,
			Version:                1,
		},
	}

	for _, p := range patients {
		if err := patientRepo.Create(ctx, p); err != nil {
			return fmt.Errorf("failed to seed patient %s: %w", p.FirstName, err)
		}
		summary.PatientsCount++
	}
	return nil
}
