import type { CountryConfig } from "../../bindings/github.com/LibreDental/libredental/pkg/domain/models.js";

export const defaultCountryConfig: CountryConfig = {
  code: "US",
  name: "United States",
  national_id_name: "Social Security Number (SSN)",
  national_id_type: "ssn",
  national_id_placeholder: "000-00-0000",
  default_tooth_system: "universal",
  default_currency: "USD",
  state_province_label: "State",
  postal_code_label: "ZIP Code",
  date_format: "MM/DD/YYYY",
};

export const FALLBACK_COUNTRIES: CountryConfig[] = [
  {
    code: "US",
    name: "United States",
    national_id_name: "Social Security Number (SSN)",
    national_id_type: "ssn",
    national_id_placeholder: "000-00-0000",
    default_tooth_system: "universal",
    default_currency: "USD",
    state_province_label: "State",
    postal_code_label: "ZIP Code",
    date_format: "MM/DD/YYYY",
  },
  {
    code: "CA",
    name: "Canada",
    national_id_name: "Social Insurance Number (SIN)",
    national_id_type: "sin",
    national_id_placeholder: "000-000-000",
    default_tooth_system: "fdi",
    default_currency: "CAD",
    state_province_label: "Province",
    postal_code_label: "Postal Code",
    date_format: "YYYY-MM-DD",
  },
  {
    code: "GB",
    name: "United Kingdom",
    national_id_name: "NHS Number",
    national_id_type: "nhs_number",
    national_id_placeholder: "000 000 0000",
    default_tooth_system: "fdi",
    default_currency: "GBP",
    state_province_label: "County",
    postal_code_label: "Postcode",
    date_format: "DD/MM/YYYY",
  },
  {
    code: "AU",
    name: "Australia",
    national_id_name: "Medicare Card Number",
    national_id_type: "medicare_num",
    national_id_placeholder: "0000 00000 0",
    default_tooth_system: "fdi",
    default_currency: "AUD",
    state_province_label: "State",
    postal_code_label: "Postcode",
    date_format: "DD/MM/YYYY",
  },
  {
    code: "DE",
    name: "Germany",
    national_id_name: "Tax / Health Insurance ID",
    national_id_type: "tax_id",
    national_id_placeholder: "X000000000",
    default_tooth_system: "fdi",
    default_currency: "EUR",
    state_province_label: "State / Bundesland",
    postal_code_label: "PLZ (Postal Code)",
    date_format: "DD.MM.YYYY",
  },
  {
    code: "FR",
    name: "France",
    national_id_name: "NIR (Numéro SS)",
    national_id_type: "nir",
    national_id_placeholder: "1 00 00 00 000 000 00",
    default_tooth_system: "fdi",
    default_currency: "EUR",
    state_province_label: "Region / Department",
    postal_code_label: "Code Postal",
    date_format: "DD/MM/YYYY",
  },
];
